### ISSUE TITLE
changes the startpage to NON USABLE

### ISSUE THREAD

**Issue by MacDos** [tombulled/search#1]
You have made me a hole day in searching this failure. 
In Deutsch:
Die komplette Autovervollständigung ist weg und die Webseite Verknüpfungen auf der Startleiste sind leer mit dem letzten Update.
Verdammt, bin sauer auf Dich.

**Comment by tombulled** [comment]
I appreciate you're frustrated, however I'd recommend you adopt a more civil and professional tone going forward. ([GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines#building-a-strong-community))

Respectfully, these extensions are about as simple as they come. Feel free to look through them and see that they do nothing that should upset your browser. This sounds like you may have encountered a bug with Firefox, I'd recommend you raise this as an issue with them here - https://bugzilla.mozilla.org/home

If you're able to provide reproducible steps I can try and replicate the issue on my end and see if I'm able to help arrive at a solution.

**Comment by MacDos** [comment]
![grafik](https://user-images.githubusercontent.com/28455864/134638175-bdcf4996-cbce-455a-874e-c06be30219b3.png)
You have not this? Prove me, I'm wrong.
Without your add-on everything is fine on my pc.

**Comment by MacDos** [comment]
![grafik](https://user-images.githubusercontent.com/28455864/134638985-8e66d136-f61a-41bb-ac40-4701ab9da425.png)
After restart Firefox without your ebay addon.
And autofill suggestion on searching works also only without it.

**Comment by tombulled** [comment]
I have been unable to reproduce this issue. These extensions have now been removed from Firefox Add-ons.
